layout_spectrum: 0.5130045395344496
typography_spectrum: 0.6413387362845242
color:
  brandColors:
    - '#FFFFFF'
    - '#013C8A'
    - '#93E265'
    - '#7993AC'
    - '#0D0C11'
  brandStrength: 0.2652236020658165
  lightness: 0.9670618947129697
  saturation: 0.09758382919244468
  rhythmicContrast: 0.6326606357470155
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-69459593-2
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29a625f4-c2e9-4db5-8fcc-a7b8150c97ef.png
name: Bridge Alliance Blog
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b33aaad7-b5a1-42e3-9bc0-890186810115.png
title: Bridge Alliance Blog
description: Connecting Corporations with Startups
purpose: []
