name: Bridge Alliance Blog
favicon: null
layout_spectrum: 0.2574
typography_spectrum: 0.52125
title: Bridge Alliance Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69459593-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#013c8a'
    - '#93e265'
    - '#7993ac'
    - '#0d0c11'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
