name: BridgeNTX
favicon: null
layout_spectrum: 0.7811097290832549
typography_spectrum: 0.005416314583271742
title: Research and Insights from Bridge Alliance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69459593-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9214402397628874
  lightness: 0.3374828207306564
  saturation: 0.004073271993547678
  rhythmicContrast: 0.26124732568860054
purpose: []
