typography_spectrum: 0.52125
color:
  brandColors:
    - '#ffffff'
    - '#013c8a'
    - '#93e265'
    - '#7993ac'
    - '#0d0c11'
  brandStrength: 0.3125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2574
analytics:
  google: UA-69459593-2
  facebook: null
  twitter: null
name: Bridge Alliance Blog
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Bridge Alliance Blog
description: Connecting Corporations with Startups
purpose: []
