name: BridgeNTX
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24237
title: Bridge Alliance Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69459593-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#717171'
    - '#fedc00'
    - '#06019b'
    - '#c747ff'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
